resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/MarcialRosales/dot-net-core-pcf-workshop
    branch: master  
    paths: 
      - simple-apps/2-sample-dotnet-core

- name: pcf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-user}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: false


jobs:
- name: build-app
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/simple-apps/2-sample-dotnet-core/ci/tasks/build.yml
  - put: pcf 
    params:
      manifest: source-code/simple-apps/2-sample-dotnet-core/manifest.yml
      path: artifact 
      environment_variables:
        ASPNETCORE_ENVIRONMENT: Production
