platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet

inputs:
- name: source-code

outputs:
- name: artifact

params:
  PROJECT: simple-apps/2-sample-dotnet-core
run:
  path: sh
  args: ["source-code/simple-apps/2-sample-dotnet-core/ci/tasks/build.sh"]